FROM scratch

ARG ISO_FILE=SERVER_EVAL.iso

LABEL org.opencontainers.image.vendor="00o-sh"
LABEL org.opencontainers.image.licenses="Proprietary"
LABEL org.opencontainers.image.source="https://github.com/00o-sh/container-images"
LABEL org.opencontainers.image.documentation="https://github.com/00o-sh/container-images/tree/main/containerdisk-windows-server"

ADD ${ISO_FILE} /disk/disk.img
